### Site info:
title: "{ blog.sunix.org }"
tagline: "Java Devops AI and FOSS"
author: Sun Seng David TAN (a.k.a Sunix)
email: sunix@sunix.org
description: "Sunix's personal blog site about Java, Cloud, and Open Source Software Development."
keywords: "sunix. Java. Cloud. Software Development. FOSS. Open Source. Eclipse JKube. Fabric8 Kubernetes Java Client. Eclipse Che. Eclipse Theia. ParisJUG. Devoxx France. Java Community. Java Champion. JavaOne. Oracle Code One. EclipseCon. EclipseCon Europe"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.sunix.org" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: __sunix_
bluesky_username: sunix.org
linkedin_username: sun-seng-david-tan-b05a684
github_username:  sunix
disqus_shortname: sunix
favicon:     "/images/favicon.ico"
aboutme: Sun Seng David TAN (a.k.a Sunix) is an experienced software engineer and tech lead with over 15 years of expertise in developing Java applications and cloud-native solutions. Formerly at Red Hat, he has contributed extensively to major open-source projects such as Eclipse JKube, Fabric8 Kubernetes Java Client, Eclipse Che, and Eclipse Theia. As a passionate advocate for the Java community, Sun served as the ParisJUG Leader from 2019 to 2023 and has been an active crew member since 2015. He also supported Devoxx France as part of the "gilets rouges" team, playing a key role in organizing one of Europe's largest developer events. In 2024, Sun joined Sciam as a tech lead consultant, bringing his expertise in guiding companies toward innovative and high-performing solutions. Passionate about continuous learning and knowledge sharing, Sun regularly speaks at conferences and remains involved in numerous open-source projects. In his spare time, Sun brews his own beer in his kitchen, combining his passion for technology and artisanal creation.
aboutme_photo: https://secure.gravatar.com/avatar/b1f5e51435209676f03b1332e7fcf405?&s=200 # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,bluesky,linkedin,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Freshman
        href: http://yulijia.net/freshman
        title: Another Jekyll blog theme
      - name: author's website
        href: http://yulijia.net/
        title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
excerpt_separator: <!-- more -->

gems: [jekyll-paginate]
