### Site info:
title: "{ blog.sunix.org }"
tagline: "Java Eclipse Che Codenvy Nuxeo Linux Cloud"
author: Sun Seng David TAN (a.k.a Sunix)
email: sunix@sunix.org
description: "Sunix's blog site about Java, Eclipse, software development and FOSS"
keywords: "sunix. Java. Eclipse. Che. Codenvy. Nuxeo"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.sunix.org" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: sunsengdavidtan
github_username:  sunix
disqus_shortname: sunix
favicon:     "/images/favicon.ico"
aboutme: Hi there, I'm Sun Seng David TAN (a.k.a. Sunix), a Java software developer working for Serli. I'm a Codenvy/Eclipse Che commiter. As a developer and a team leader, I'm working on the SaaS developer environment Codenvy. I've previously worked as a Java developer for Nuxeo, the Enterprise Content Management framework.
aboutme_photo: https://secure.gravatar.com/avatar/b1f5e51435209676f03b1332e7fcf405?&s=200 # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Freshman
        href: http://yulijia.net/freshman
        title: Another Jekyll blog theme
      - name: author's website
        href: http://yulijia.net/
        title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
excerpt_separator: <!-- more -->

gems: [jekyll-paginate]
