# Quarkus Configuration
quarkus.application.name=blog-sunix-org

# Roq Configuration
quarkus.roq.site.title={ blog.sunix.org }
quarkus.roq.site.description=Sunix's personal blog site about Java, Cloud, and Open Source Software Development.
quarkus.roq.site.url=https://blog.sunix.org
quarkus.roq.site.author=Sun Seng David TAN (a.k.a Sunix)

# Enable static file generation
quarkus.roq.generator.static=true

# Development mode configuration
%dev.quarkus.http.port=4000
%dev.quarkus.log.level=INFO

# Production configuration
%prod.quarkus.http.port=8080
